import type { TKDB_Tag } from './tkdb_json/tkdb.model';
export const Tags: TKDB_Tag = {
  jlpt: {
    n1: 'JLPT N1',
    n2: 'JLPT N2',
    n3: 'JLPT N3',
    n4: 'JLPT N4',
    n5: 'JLPT N5',
  },
  kanjiReadingType: {
    kun: 'Kun',
    nanori: 'Nanori',
    on: 'On',
  },
  kanjiGrade: {
    jinmeiyou1: 'Jinmeiyou',
    jinmeiyou2: 'Jinmeiyou',
    jouyou: 'Jouyou',
    kyouiku1: 'Kyouiku 1st grade',
    kyouiku2: 'Kyouiku 2nd grade',
    kyouiku3: 'Kyouiku 3rd grade',
    kyouiku4: 'Kyouiku 4th grade',
    kyouiku5: 'Kyouiku 5th grade',
    kyouiku6: 'Kyouiku 6th grade',
  },
  kanjiCodepointType: {
    jis208: 'JIS X 0208',
    jis212: 'JIS X 0212',
    jis213: 'JIS X 0213',
    ucs: 'Unicode',
  },
  kanjiDicrefType: {
    busyPeople: 'Japanese For Busy People by AJLT',
    crowley: 'The Kanji Way to Japanese Language Power by Dale Crowley',
    gakken: 'A New Dictionary of Kanji Usage by Gakken',
    halpernKkd: 'Kodansha Kanji Dictionary by Jack Halpern',
    halpernKkld: 'Kadonsha Kanji Learners Dictionary by Jack Halpern',
    halpernKkld2ed: "Kodansha Kanji Learner's Dictionary, 2nd Edition by Jack Halpern",
    halpernNjecd: 'New Japanese English Character Dictionary by Jack Halpern',
    heisig: 'Remembering The  Kanji by James Heisig',
    heisig6: 'Remembering The Kanji, 6th edition by James Heisig',
    henshall: 'A Guide To Reading and Writing Japanese by Kenneth G. Henshall',
    henshall3: 'A Guide To Reading and Writing Japanese, 3rd edition by Henshall, Seeley and De Groot',
    jfCards: 'Japanese Kanji Flashcards by Max Hodges and Tomoko Okazaki',
    kanjiInContext: 'Kanji in Context by Nishiguchi and Kono',
    kodanshaCompact: 'Kodansha Compact Kanji Guide',
    maniette: 'Les Kanjis dans la tete by Yves Maniette',
    moro: 'Daikanwajiten by Morohashi',
    nelsonC: "Modern Reader's Japanese-English Character Dictionary by Andrew Nelson",
    nelsonN: 'The New Nelson Japanese-English Character Dictionary by John Haig',
    oneillKk: "Essential Kanji by P.G. O'Neill",
    oneillNames: "Japanese Names by P.G. O'Neill",
    sakade: 'A Guide To Reading and Writing Japanese by Florence Sakade',
    shKk: 'Kanji and Kana by Spahn and Hadamitzky',
    shKk2: 'Kanji and Kana 2nd Edition by Spahn and Hadamitzky',
    tuttCards: 'Tuttle Kanji Cards by Alexander Kask',
  },
  kanjiQuerycodeType: {
    deroo: '2001 Kanji',
    fourCorner: 'Four Corner code',
    shDesc: 'The Kanji Dictionary',
    skip: 'SKIP',
  },
  wordMeaningDial: {
    bra: 'Brazilian',
    hob: 'Hokkaido-ben',
    ksb: 'Kansai-ben',
    ktb: 'Kantou-ben',
    kyb: 'Kyoto-ben',
    kyu: 'Kyuushuu-ben',
    nab: 'Nagano-ben',
    osb: 'Osaka-ben',
    rkb: 'Ryuukyuu-ben',
    thb: 'Touhoku-ben',
    tsb: 'Tosa-ben',
    tsug: 'Tsugaru-ben',
  },
  wordMeaningField: {
    agric: 'agriculture',
    anat: 'anatomical',
    archeol: 'archeology',
    archit: 'architecture',
    art: 'art',
    astron: 'astronomy',
    audvid: 'audiovisual',
    aviat: 'aviation',
    baseb: 'baseball',
    biochem: 'biochemistry',
    biol: 'biology',
    bot: 'botany',
    buddh: 'Buddhism',
    bus: 'business',
    cards: 'card games',
    chem: 'chemistry',
    christn: 'Christianity',
    cloth: 'clothing',
    comp: 'computer',
    cryst: 'crystallography',
    dent: 'dentistry',
    ecol: 'ecology',
    econ: 'economics',
    elec: 'electricity',
    electr: 'electronics',
    engr: 'engineering',
    ent: 'entomology',
    finc: 'finance',
    fish: 'fishing',
    food: 'food',
    gardn: 'gardening',
    genet: 'genetics',
    geogr: 'geography',
    geol: 'geology',
    geom: 'geometry',
    go: 'go (game)',
    golf: 'golf',
    gramm: 'grammar',
    grmyth: 'Greek mythology',
    hanaf: 'hanafuda (game)',
    horse: 'horse racing',
    kabuki: 'kabuki',
    law: 'law',
    ling: 'linguistics',
    logic: 'logic',
    ma: 'martial arts',
    mahj: 'mahjong',
    math: 'mathematics',
    mech: 'mechanical engineering',
    med: 'medicine',
    met: 'meteorology',
    mil: 'military',
    music: 'music',
    ornith: 'ornithology',
    paleo: 'paleontology',
    pathol: 'pathology',
    pharm: 'pharmacology',
    phil: 'philosophy',
    photo: 'photography',
    physics: 'physics',
    physiol: 'physiology',
    politics: 'politics',
    print: 'printing',
    psy: 'psychiatry',
    psych: 'psychology',
    rail: 'railway',
    shinto: 'Shinto',
    shogi: 'shogi',
    sports: 'sports',
    stat: 'statistics',
    sumo: 'sumo',
    telec: 'telecommunications',
    tradem: 'trademark',
    vidg: 'video games',
    zool: 'zoology',
  },
  wordMeaningGlossType: {
    expl: 'explanation',
    fig: 'figurative',
    lit: 'literal',
    tm: 'trademark',
  },
  wordMeaningMisc: {
    mSl: 'manga slang',
    netSl: 'internet slang',
    onMim: 'onomatopoeic or mimetic word',
    abbr: 'abbreviation',
    arch: 'archaic',
    chn: "children's language",
    col: 'colloquialism',
    dated: 'dated term',
    derog: 'derogatory',
    euph: 'euphemistic',
    fam: 'familiar language',
    fem: 'female term or language',
    form: 'formal or literary term',
    hist: 'historical term',
    hon: 'honorific or respectful (sonkeigo) language',
    hum: 'humble (kenjougo) language',
    id: 'idiomatic expression',
    joc: 'jocular, humorous term',
    leg: 'legend',
    male: 'male term or language',
    obs: 'obsolete term',
    person: 'name of a particular person',
    place: 'place name',
    poet: 'poetical',
    pol: 'polite (teineigo) language',
    proverb: 'proverb',
    quote: 'quotation',
    rare: 'rare',
    sens: 'sensitive',
    sl: 'slang',
    uk: 'word usually written using kana alone',
    vulg: 'vulgar expression or word',
    work: 'work of art, literature, music, etc. name',
    yoji: 'yojijukugo',
  },
  wordMeaningPos: {
    adjF: 'noun or verb acting prenominally',
    adjI: 'adjective (keiyoushi)',
    adjIx: 'adjective (keiyoushi) - yoi/ii class',
    adjKu: '"ku" adjective (archaic)',
    adjNa: 'adjectival nouns or quasi-adjectives (keiyodoshi)',
    adjNari: 'archaic/formal form of na-adjective',
    adjNo: 'nouns which may take the genitive case particle "no"',
    adjPn: 'pre-noun adjectival (rentaishi)',
    adjShiku: '"shiku" adjective (archaic)',
    adjT: '"taru" adjective',
    adv: 'adverb (fukushi)',
    advTo: 'adverb taking the "to" particle',
    aux: 'auxiliary',
    auxAdj: 'auxiliary adjective',
    auxV: 'auxiliary verb',
    conj: 'conjunction',
    cop: 'copula',
    ctr: 'counter',
    exp: 'expressions',
    int: 'interjection (kandoushi)',
    n: 'noun (common) (futsuumeishi)',
    nPref: 'noun, used as a prefix',
    nSuf: 'noun, used as a suffix',
    num: 'numeric',
    pn: 'pronoun',
    pref: 'prefix',
    prt: 'particle',
    suf: 'suffix',
    unc: 'unclassified',
    v1: 'ichidan verb',
    v1S: 'ichidan verb - kureru special class',
    v2aS: 'nidan verb with "u" ending (archaic)',
    v2bK: 'nidan verb (upper class) with "bu" ending (archaic)',
    v2dS: 'nidan verb (lower class) with "dzu" ending (archaic)',
    v2gK: 'nidan verb (upper class) with "gu" ending (archaic)',
    v2gS: 'nidan verb (lower class) with "gu" ending (archaic)',
    v2hK: 'nidan verb (upper class) with "hu/fu" ending (archaic)',
    v2hS: 'nidan verb (lower class) with "hu/fu" ending (archaic)',
    v2kK: 'nidan verb (upper class) with "ku" ending (archaic)',
    v2kS: 'nidan verb (lower class) with "ku" ending (archaic)',
    v2mS: 'nidan verb (lower class) with "mu" ending (archaic)',
    v2nS: 'nidan verb (lower class) with "nu" ending (archaic)',
    v2rK: 'nidan verb (upper class) with "ru" ending (archaic)',
    v2rS: 'nidan verb (lower class) with "ru" ending (archaic)',
    v2sS: 'nidan verb (lower class) with "su" ending (archaic)',
    v2tK: 'nidan verb (upper class) with "tsu" ending (archaic)',
    v2tS: 'nidan verb (lower class) with "tsu" ending (archaic)',
    v2wS: 'nidan verb (lower class) with "u" ending and "we" conjugation (archaic)',
    v2yK: 'nidan verb (upper class) with "yu" ending (archaic)',
    v2yS: 'nidan verb (lower class) with "yu" ending (archaic)',
    v2zS: 'nidan verb (lower class) with "zu" ending (archaic)',
    v4b: 'yodan verb with "bu" ending (archaic)',
    v4g: 'yodan verb with "gu" ending (archaic)',
    v4h: 'yodan verb with "hu/fu" ending (archaic)',
    v4k: 'yodan verb with "ku" ending (archaic)',
    v4m: 'yodan verb with "mu" ending (archaic)',
    v4r: 'yodan verb with "ru" ending (archaic)',
    v4s: 'yodan verb with "su" ending (archaic)',
    v4t: 'yodan verb with "tsu" ending (archaic)',
    v5aru: 'godan verb - -aru special class',
    v5b: 'godan verb with "bu" ending',
    v5g: 'godan verb with "gu" ending',
    v5k: 'godan verb with "ku" ending',
    v5kS: 'godan verb - Iku/Yuku special class',
    v5m: 'godan verb with "mu" ending',
    v5n: 'godan verb with "nu" ending',
    v5r: 'godan verb with "ru" ending',
    v5rI: 'godan verb with "ru" ending (irregular verb)',
    v5s: 'godan verb with "su" ending',
    v5t: 'godan verb with "tsu" ending',
    v5u: 'godan verb with "u" ending',
    v5uS: 'godan verb with "u" ending (special class)',
    vi: 'intransitive verb',
    vk: 'kuru verb - special class',
    vn: 'irregular nu verb',
    vr: 'irregular ru verb, plain form ends with -ri',
    vs: 'noun or participle which takes the aux. verb suru',
    vsC: 'su verb - precursor to the modern suru',
    vsI: 'suru verb - irregular',
    vsS: 'suru verb - special class',
    vt: 'transitive verb',
    vUnspec: 'verb unspecified',
    vz: 'ichidan verb - zuru verb (alternative form of -jiru verbs)',
  },
  wordReadingInfo: {
    ateji: 'ateji (phonetic) reading',
    gikun: 'gikun (meaning as reading) or jukujikun (special kanji reading)',
    iK: 'word containing irregular kanji usage',
    ik: 'word containing irregular kana usage',
    io: 'irregular okurigana usage',
    oK: 'word containing out-dated kanji',
    ok: 'out-dated or obsolete kana usage',
    rK: 'rarely-used kanji form',
  },
};
